"""PDF report generation service using reportlab."""

import io
from datetime import datetime
from typing import Optional

import numpy as np

try:
    import cv2
except ImportError:
    cv2 = None

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image as RLImage,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from ..utils.logger import get_logger

logger = get_logger("services.report_generator")

HIPAA_DISCLAIMER = (
    "PRIVACY NOTICE: This report was generated by Atrophy Advisor. "
    "This tool does not store, save, or transmit any patient data. "
    "All image processing occurs within the user's session and is discarded upon completion. "
    "The user assumes all responsibility for any protected health information (PHI) "
    "included in uploaded images. For research and clinical decision support purposes only."
)


class ReportGeneratorService:
    """Generates PDF progression reports from GA analysis data."""

    def generate(
        self,
        image_before_bytes: bytes,
        image_after_bytes: bytes,
        date_before: str,
        date_after: str,
        eye_side: str,
        distance_before_microns: float,
        distance_after_microns: float,
        days_elapsed: int,
        distance_change_microns: float,
        rate_microns_per_year: Optional[float],
        rate_microns_per_month: Optional[float],
        years_until_involvement: Optional[float],
        predicted_foveal_involvement_date: Optional[str],
        status: str,
    ) -> bytes:
        """Generate PDF and return as bytes."""
        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=letter,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )

        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle(
            "title",
            parent=styles["Title"],
            fontSize=18,
            textColor=colors.HexColor("#1e3a5f"),
            spaceAfter=4,
        )
        subtitle_style = ParagraphStyle(
            "subtitle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.gray,
            spaceAfter=12,
        )
        story.append(Paragraph("Atrophy Advisor", title_style))
        story.append(Paragraph("Geographic Atrophy Progression Report", subtitle_style))
        story.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y')}", subtitle_style))

        story.append(Spacer(1, 0.15 * inch))

        # Images side by side
        img_before = self._bytes_to_rl_image(image_before_bytes, max_width=3.2 * inch, max_height=2.5 * inch)
        img_after = self._bytes_to_rl_image(image_after_bytes, max_width=3.2 * inch, max_height=2.5 * inch)

        label_style = ParagraphStyle(
            "img_label",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#444444"),
            alignment=1,
        )

        img_table_data = [
            [
                Paragraph(f"<b>Image 1 (Before)</b><br/>{self._fmt_date(date_before)}", label_style),
                Paragraph(f"<b>Image 2 (After)</b><br/>{self._fmt_date(date_after)}", label_style),
            ],
            [img_before or Paragraph("(Image unavailable)", styles["Normal"]),
             img_after or Paragraph("(Image unavailable)", styles["Normal"])],
        ]
        img_table = Table(img_table_data, colWidths=[3.35 * inch, 3.35 * inch])
        img_table.setStyle(TableStyle([
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 4),
        ]))
        story.append(img_table)
        story.append(Spacer(1, 0.2 * inch))

        # Measurements table
        section_style = ParagraphStyle(
            "section",
            parent=styles["Heading2"],
            fontSize=11,
            textColor=colors.HexColor("#1e3a5f"),
            spaceBefore=8,
            spaceAfter=4,
        )
        story.append(Paragraph("Measurements", section_style))

        measurements_data = [
            ["", "Image 1 (Before)", "Image 2 (After)"],
            ["Date", self._fmt_date(date_before), self._fmt_date(date_after)],
            ["Eye", eye_side, eye_side],
            ["GA-to-Fovea Distance", f"{distance_before_microns:.1f} µm", f"{distance_after_microns:.1f} µm"],
        ]
        meas_table = Table(measurements_data, colWidths=[2.0 * inch, 2.35 * inch, 2.35 * inch])
        meas_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f4f8")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(meas_table)
        story.append(Spacer(1, 0.15 * inch))

        # Progression analysis
        story.append(Paragraph("Progression Analysis", section_style))

        prog_rows = [
            ["Metric", "Value"],
            ["Time Elapsed", f"{days_elapsed} days"],
            ["Distance Change", f"{distance_change_microns:.1f} µm"],
        ]

        if status == "progression":
            if rate_microns_per_year is not None:
                prog_rows.append(["Rate of Progression", f"{rate_microns_per_year:.1f} µm/year  ({rate_microns_per_month:.1f} µm/month)" if rate_microns_per_month else f"{rate_microns_per_year:.1f} µm/year"])
            if years_until_involvement is not None:
                est_date = f"  (approx. {self._fmt_predicted_month(predicted_foveal_involvement_date)})" if predicted_foveal_involvement_date else ""
                prog_rows.append(["Est. Foveal Involvement", f"~{years_until_involvement:.1f} years{est_date}"])
        elif status == "no_progression":
            prog_rows.append(["Status", "No progression detected"])
        else:
            prog_rows.append(["Status", "See error — check measurements"])

        prog_table = Table(prog_rows, colWidths=[2.5 * inch, 4.2 * inch])
        prog_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f4f8")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(prog_table)

        story.append(Spacer(1, 0.3 * inch))

        # HIPAA disclaimer footer
        disclaimer_style = ParagraphStyle(
            "disclaimer",
            parent=styles["Normal"],
            fontSize=7,
            textColor=colors.HexColor("#888888"),
            borderColor=colors.HexColor("#cccccc"),
            borderWidth=0.5,
            borderPadding=6,
            leading=10,
        )
        story.append(Paragraph(HIPAA_DISCLAIMER, disclaimer_style))

        doc.build(story)
        return buf.getvalue()

    @staticmethod
    def _fmt_date(date_str: str) -> str:
        try:
            return datetime.strptime(date_str, "%Y-%m-%d").strftime("%B %d, %Y")
        except ValueError:
            return date_str

    @staticmethod
    def _fmt_predicted_month(year_month: str) -> str:
        try:
            return datetime.strptime(year_month, "%Y-%m").strftime("%B %Y")
        except ValueError:
            return year_month

    @staticmethod
    def _bytes_to_rl_image(
        image_bytes: bytes, max_width: float, max_height: float
    ) -> Optional[RLImage]:
        if cv2 is None:
            return None
        try:
            np_arr = np.frombuffer(image_bytes, np.uint8)
            img = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
            if img is None:
                return None
            img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            h, w = img_rgb.shape[:2]
            scale = min(max_width / w, max_height / h)
            disp_w = w * scale
            disp_h = h * scale
            _, encoded = cv2.imencode(".jpg", img, [cv2.IMWRITE_JPEG_QUALITY, 85])
            return RLImage(io.BytesIO(encoded.tobytes()), width=disp_w, height=disp_h)
        except Exception as exc:
            logger.warning("Could not embed image in PDF: %s", exc)
            return None
